name: autofix.ci  # needed to securely identify the workflow

on:
  pull_request:
    paths:
      - "docs/**"
      - ".github/workflows/docs.yml"
  push:
    branches:
      - "renovate/**"

permissions:
  contents: read

jobs:
  docs:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # v3.5.3
      - run: corepack enable
      - uses: actions/setup-node@e33196f7422957bea03ed53f6fbb155025ffc7b8 # v3.7.0
        with:
          node-version: 20
          cache: "pnpm"

      - name: Install dependencies
        run: pnpm install

      - name: Lint (docs)
        run: pnpm lint:docs:fix

      - uses: autofix-ci/action@ea32e3a12414e6d3183163c3424a7d7a8631ad84
