name: docs-e2e

on:
  workflow_dispatch:
    inputs:
      url:
        required: false
        description: The URL to run the test suite against.
        type: string
  deployment_status:

permissions:
  contents: read

jobs:
  crawl-docs:
    environment:
      name: ${{ github.event.deployment.environment || 'Production' }}
      url: ${{ github.event.inputs.url || github.event.deployment.payload.web_url || github.event.deployment_status.target_url }}
    if: github.event.deployment_status.state == 'success' || github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
      - run: corepack enable
      - uses: actions/setup-node@e33196f7422957bea03ed53f6fbb155025ffc7b8 # v3.7.0
        with:
          cache: "pnpm"

      - name: Install dependencies
        run: pnpm install

      - run: node ./scripts/crawl.mjs
        env:
          BASE_URL: ${{ github.event.inputs.url || github.event.deployment.payload.web_url || github.event.deployment_status.target_url }}
